#!/usr/bin/env python3
from __future__ import annotations

import json
from pathlib import Path
from playwright.sync_api import sync_playwright

ROOT=Path(__file__).resolve().parents[2]
OUT=ROOT/'partener-eu'/'ops'/'ux-concierge-vnext-proof.json'
SHOT_DIR=ROOT/'partener-eu'/'ops'/'ux-concierge-vnext-screenshots'
BASE_URL='http://127.0.0.1:4173/index.html'
SHOT_DIR.mkdir(parents=True,exist_ok=True)


def audit(browser,name:str,width:int,height:int)->dict:
    page=browser.new_page(viewport={'width':width,'height':height})
    errors:list[str]=[]
    console_errors:list[str]=[]
    failed_responses:list[dict]=[]
    page.on('console',lambda msg: console_errors.append(msg.text) if msg.type=='error' else None)
    page.on('pageerror',lambda exc: console_errors.append(str(exc)))
    page.on('response',lambda r: failed_responses.append({'status':r.status,'url':r.url}) if r.status>=400 else None)
    page.goto(BASE_URL,wait_until='networkidle',timeout=60000)
    page.wait_for_timeout(1100)

    if page.locator('body.conciergeHome').count()!=1:
        errors.append('concierge home mode did not initialize')
    if page.locator('.conciergeHero h1').inner_text().strip()!='Ce vrei să finanțezi?':
        errors.append('human-first hero headline missing')
    if page.locator('.conciergeSearch input').count()!=1 or not page.locator('.conciergeSearch input').is_visible():
        errors.append('primary natural-language search missing or hidden')
    if page.locator('.conciergeProfiles button').count()<5:
        errors.append('profile shortcuts incomplete')

    # Regression: the primary search field must remain the same live input while
    # the user types. Re-rendering/replacing it makes desktop input drop text and
    # prevents mobile soft keyboards from staying open.
    qhome=page.locator('.conciergeSearch input')
    marker='hala productie utilaje valcea'
    qhome.click()
    qhome.type(marker,delay=35)
    page.wait_for_timeout(700)
    if qhome.input_value()!=marker:
        errors.append('primary search input lost or rejected typed text')
    if not page.evaluate("document.activeElement===document.querySelector('.conciergeSearch input')"):
        errors.append('primary search input lost focus while typing')
    for selector,label in (
        ('.conciergeOpen','open calls section'),
        ('.conciergeUpcoming','upcoming section'),
        ('.conciergeChanges','changes section'),
        ('.conciergeTrust','trust section'),
    ):
        if page.locator(selector).count()!=1 or not page.locator(selector).is_visible():
            errors.append(f'{label} missing or hidden')

    # Superseded homepage surfaces may still exist as canonical DOM generated by
    # generic modules, but they must not be visible to the public homepage.
    for selector,label in (
        ('.dailyBrief','legacy daily briefing'),
        ('.noviceEntry','legacy novice entry'),
        ('.gotoOrientation','legacy orientation'),
        ('.gotoPromise','legacy promise layer'),
        ('.diHome','technical decision-intelligence homepage'),
    ):
        loc=page.locator(selector)
        if loc.count() and loc.first.is_visible():
            errors.append(f'{label} remains visible')

    # OPEN surface must never contain cards that are absent from the strict
    # frontend gate when re-evaluated against canonical decision products.
    open_ids=page.eval_on_selector_all('.conciergeOpen [data-concierge-dossier]','els=>els.map(e=>e.dataset.conciergeDossier)')
    gate=page.evaluate('''() => {
      const P=window.PARTENER_HOME_DATA||{};
      const norm=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\\u0300-\\u036f]/g,'');
      const overrides=P.freshnessGuard?.dossierStatusOverrides||{};
      const status=d=>overrides[d?.id]||d?.status||'REVIEW';
      const fact=(d,l)=>d?.quickFacts?.find(x=>norm(x?.label)===norm(l));
      const confirmed=(d,l)=>{const x=fact(d,l);return x&&String(x.confidence||'').toUpperCase()==='CONFIRMED'?x:null};
      const parse=v=>{const d=new Date(v);return Number.isNaN(d.getTime())?null:d};
      return (P.dossiers||[]).filter(d=>{
        if(status(d)!=='OPEN'||String(d.publicationState||'').toUpperCase()!=='PUBLISHABLE')return false;
        if(!confirmed(d,'Status'))return false;
        const deadline=confirmed(d,'Termen');if(!deadline)return false;
        const dt=parse(deadline.value);return !!(dt&&dt.getTime()>=Date.now());
      }).map(d=>d.id);
    }''')
    invalid=[x for x in open_ids if x not in gate]
    if invalid:
        errors.append(f'open cards bypass strict gate: {invalid[:5]}')

    lazy_state=page.evaluate('''() => ({
      decisionProductsLoaded: !!window.PARTENER_DECISION_PRODUCTS,
      canonicalCallsLoaded: !!window.PARTENER_MIPE_CANONICAL_CALLS,
      lifecycleLoaded: !!window.PARTENER_CALL_LIFECYCLE,
      homeSnapshotLoaded: !!window.PARTENER_HOME_DATA
    })''')
    if not lazy_state['homeSnapshotLoaded']:
        errors.append('compact home snapshot did not load')
    if lazy_state['decisionProductsLoaded'] or lazy_state['canonicalCallsLoaded'] or lazy_state['lifecycleLoaded']:
        errors.append(f"heavy public data loaded eagerly: {lazy_state}")

    metrics=page.evaluate('''() => ({
      scrollWidth:document.documentElement.scrollWidth,
      clientWidth:document.documentElement.clientWidth,
      heroWidth:document.querySelector('.conciergeHero')?.getBoundingClientRect().width||0,
      searchWidth:document.querySelector('.conciergeSearch')?.getBoundingClientRect().width||0
    })''')
    if metrics['scrollWidth']-metrics['clientWidth']>2:
        errors.append(f"horizontal overflow: {metrics['scrollWidth']-metrics['clientWidth']}px")

    # Verify that the profile shortcut enters the lightweight base explorer and
    # carries its natural-language query without loading multi-megabyte datasets.
    if name.startswith('desktop'):
        page.locator('.conciergeProfiles button').first.click()
        page.wait_for_load_state('networkidle')
        page.wait_for_timeout(500)
        if page.locator('.resultbar').count()!=1:
            errors.append('profile shortcut did not open lightweight explorer')
        q=page.locator('#fq')
        if q.count()!=1 or 'firm' not in q.input_value().lower():
            errors.append('profile shortcut did not carry its query into explorer search')
        after=page.evaluate('''() => ({
          decisionProductsLoaded: !!window.PARTENER_DECISION_PRODUCTS,
          canonicalCallsLoaded: !!window.PARTENER_MIPE_CANONICAL_CALLS
        })''')
        if after['decisionProductsLoaded'] or after['canonicalCallsLoaded']:
            errors.append(f'profile discovery loaded heavy datasets: {after}')

    shot=SHOT_DIR/f'{name}.png'
    page.screenshot(path=str(shot),full_page=True)
    result={
        'viewport':{'name':name,'width':width,'height':height},
        'openCardIds':open_ids,
        'strictGateIds':gate,
        'metrics':metrics,
        'lazyState':lazy_state,
        'failedResponses':failed_responses,
        'consoleErrors':console_errors,
        'errors':errors,
        'screenshot':shot.relative_to(ROOT).as_posix(),
    }
    page.close()
    return result


def main()->int:
    with sync_playwright() as p:
        browser=p.chromium.launch(channel='chrome',headless=True,args=['--no-sandbox'])
        results=[audit(browser,'desktop-1365x900',1365,900),audit(browser,'mobile-390x844',390,844)]
        browser.close()
    errors=[f"{r['viewport']['name']}: {e}" for r in results for e in r['errors']]
    console=[f"{r['viewport']['name']}: {e}" for r in results for e in r['consoleErrors']]
    failed=[x for r in results for x in r['failedResponses']]
    status='PASS' if not errors and not console and not failed else 'FAIL'
    proof={'schema':'PARTENER_UX_CONCIERGE_VNEXT_PROOF','status':status,'baseUrl':BASE_URL,'results':results,'errors':errors,'consoleErrors':console,'failedResponses':failed}
    OUT.write_text(json.dumps(proof,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
    print(json.dumps(proof,ensure_ascii=False,indent=2))
    return 0 if status=='PASS' else 1

if __name__=='__main__':
    raise SystemExit(main())
