(()=>{
const D=window.PARTENER_DATA=window.PARTENER_DATA||{};
const OIR='https://www.runv.ro/anunturi.html';
const GUIDE='https://mfe.gov.ro/wp-content/uploads/2026/05/b3ab74f4a3eefb8a6ec443cd00a57d00.7z';
const QA='https://mfe.gov.ro/wp-content/uploads/2026/05/2d29521843aea5d626d0e1879a1a9ce6.pdf';
const EC='https://employment-social-affairs.ec.europa.eu/policies-and-activities/skills-and-qualifications/alma-active-inclusion-initiative-young-people_ro';
const HANDBOOK='https://european-social-fund-plus.ec.europa.eu/system/files/2024-02/ALMA%20Handbook.pdf';
const PREF='https://vn.prefectura.mai.gov.ro/oportunitati-de-finantare-apl_06-2026/';
const DOCS=[
 {name:'Pachet final Ghidul Solicitantului – Inițiativa ALMA',meta:'7Z · 2,06 MB · MIPE · lansare 27.05.2026',url:GUIDE},
 {name:'Răspunsuri la propunerile, observațiile și întrebările din consultare',meta:'PDF · 339,90 KB · AM PEO · 26.05.2026',url:QA},
 {name:'ALMA Handbook – European Commission',meta:'PDF · 1,41 MB · ghid practic european de implementare',url:HANDBOOK}
];
D.almaStory={id:'peo-alma-2026',status:'OPEN',headline:'Inițiativa ALMA: până la 850.000 € pentru proiecte dedicate tinerilor NEET, cu mobilitate obligatorie în UE',deadline:'28 august 2026 · 16:00',budget:'19.714.235 €',lessDeveloped:'17.731.146,50 €',project:'201.000–850.000 €',documents:DOCS};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c));
function render(){const main=document.querySelector('.main');if(!main)return;const s=D.almaStory;main.innerHTML=`<article class="almaArticle">
<header class="almaHero"><button class="btn ghost almaBack">← Înapoi</button><div class="almaTags"><span>PEO</span><span>PRIORITATEA 2</span><span>TINERI NEET</span><span class="open">OPEN</span></div><h1>${esc(s.headline)}</h1><p>Inițiativa ALMA este un apel PEO dedicat integrării tinerilor NEET printr-un parcurs complet: identificare și pregătire personalizată, experiență profesională supravegheată într-un alt stat membru al Uniunii Europene și sprijin pentru revenirea în educație, formare sau ocupare după întoarcerea în România.</p><div class="almaMeta">Lansat: 27 mai 2026 · MySMIS: 28 mai–28 august 2026, ora 16:00 · analiză PARTENER.EU: 11 august 2026</div></header>
<section class="almaFacts"><div><small>Buget total</small><b>19,71 mil. €</b></div><div><small>Regiuni mai puțin dezvoltate</small><b>17,73 mil. €</b></div><div><small>Valoare proiect</small><b>201k–850k €</b></div><div><small>Grup țintă</small><b>16–29 ani</b></div><div><small>Deadline</small><b>28.08.2026</b></div></section>
<section class="almaBlock important"><h2>Status acum</h2><p><b>Apelul este OPEN.</b> OIR PECU Nord‑Vest publică lansarea oficială a apelului competitiv și intervalul MySMIS: <b>28.05.2026, ora 16:00 – 28.08.2026, ora 16:00</b>. Apelul acoperă regiunile eligibile stabilite prin ghid, cu alocări distincte pentru regiunile mai puțin dezvoltate și pentru regiunea București–Ilfov.</p></section>
<section class="almaBlock"><h2>Cine poate depune</h2><div class="almaBullets"><div><b>ONG-uri / asociații / fundații</b><br>Inclusiv organizații de și pentru tineret cu experiență în ocupare sau formare.</div><div><b>Furnizori FPC</b><br>Publici sau privați, autorizați conform legii.</div><div><b>Școli și instituții de învățământ</b><br>Învățământ profesional/tehnic, postliceal și universități acreditate.</div><div><b>Furnizori de ocupare și servicii sociale</b><br>Entități publice/private acreditate, inclusiv SPO.</div><div><b>Angajatori și întreprinderi sociale</b><br>Întreprinderi publice/private și întreprinderi sociale/de inserție.</div><div><b>Parteneri sociali / fundații de tineret</b><br>Inclusiv Fundația Națională pentru Tineret și fundațiile județene.</div></div><p class="almaCaution">Finalul consultării a flexibilizat parteneriatul: proiectul poate fi depus de un solicitant unic sau în parteneriat. Dacă SPO nu este solicitant/lider/partener, implicarea lui se asigură ca partener asociat. Liderul unui parteneriat trebuie să fie o entitate înregistrată fiscal în România.</p></section>
<section class="almaBlock"><h2>Grupul țintă</h2><p>Tineri NEET care la intrarea în operațiune au <b>împlinit 16 ani și nu au împlinit 30 de ani</b>, au domiciliul/reședința în regiunea vizată și nu sunt în ocupare, educație sau formare. Varianta finală a eliminat obligativitatea adeverinței SPO pentru dovedirea statutului la intrarea în grupul țintă, conform răspunsurilor AM PEO.</p><p><b>Atenție la indicator:</b> ținta minimă obligatorie pentru indicatorul 5SO05 „Copii și tineri roma” rămâne <b>minimum 9%</b> din valoarea asumată pentru EECO06+07.</p></section>
<section class="almaBlock"><h2>Ce finanțează efectiv</h2><div class="almaBullets"><div><b>1. Identificare, activare și pregătire personalizată</b><br>Outreach, evaluare, consiliere, pregătire pentru mobilitate și plan individual.</div><div><b>2. Mobilitate transnațională</b><br>Experiență profesională supravegheată într-o întreprindere/instituție din alt stat membru UE.</div><div><b>3. Reintegrare după revenire</b><br>Sprijin pentru ocupare, activitate independentă, reluarea educației sau formării și monitorizarea rezultatului.</div><div><b>Costuri pentru participant</b><br>Călătorie, asigurare, cazare, hrană/nevoi de bază, mentorat și consiliere sunt tipuri de costuri prevăzute de mecanismul ALMA.</div></div></section>
<section class="almaBlock important"><h2>Cele 5 lucruri care pot face sau rupe proiectul</h2><div class="almaRiskGrid"><div class="almaRisk"><b>Mobilitatea nu este opțională.</b><br>Tinerii trebuie să petreacă între <b>2 și 6 luni</b> într-un alt stat UE.</div><div class="almaRisk"><b>Pragul de 30% este dur.</b><br>AM PEO a clarificat că mobilitatea trebuie să reprezinte minimum <b>30% din durata totală de implementare a proiectului</b>.</div><div class="almaRisk"><b>Ai nevoie de organizație gazdă.</b><br>Trebuie construită o relație operațională transnațională și o convenție care acoperă stagiul, condițiile de trai și rambursarea cheltuielilor.</div><div class="almaRisk"><b>Rezultatul se urmărește acasă.</b><br>Logica ALMA este revenirea în România și integrarea în muncă/educație; Q&A precizează că indicatorul de ocupare vizează piața muncii din România.</div><div class="almaRisk"><b>Recrutarea NEET este critică.</b><br>Trebuie construit pipeline-ul real de outreach, validare, menținere și pregătire înainte de plecare, inclusiv ținta de minimum 9% tineri romi.</div><div class="almaRisk"><b>Capacitatea de implementare contează.</b><br>Bugetele pot urca la 850.000 €, iar proiectul combină management local, mobilitate internațională, mentorat, monitorizare și rezultate post-mobilitate.</div></div></section>
<section class="almaBlock"><h2>Ce trebuie făcut acum</h2><ol class="almaSteps"><li><b>GO/NO-GO pe eligibilitatea organizației</b> și experiența cerută pentru categoria în care intră solicitantul.</li><li><b>Definirea teritoriului de implementare</b>: un județ, grup de județe, o regiune sau mai multe regiuni, în limitele geografice prevăzute de ghid.</li><li><b>Identificarea organizației gazdă din alt stat UE</b> și verificarea capacității reale de a organiza stagii de 2–6 luni.</li><li><b>Construirea pipeline-ului de grup țintă</b>: surse de recrutare, criterii NEET, documente, rată de abandon și rezervă de participanți.</li><li><b>Simularea duratei</b>: mobilitatea trebuie să rămână ≥30% din durata totală a proiectului.</li><li><b>Planul de reintegrare în România</b>: angajatori, formare, școală, ocupare și urmărirea rezultatului la 6 luni.</li><li><b>Buget și cash-flow</b>: verificarea mecanismului de costuri unitare/finanțare nelegată de costuri și a eventualelor costuri neeligibile.</li><li><b>Citirea integrală a pachetului final și Q&A</b> înainte de blocarea arhitecturii proiectului.</li></ol></section>
<section class="almaBlock"><h2>Documente oficiale și de implementare</h2><p>Pachetul final MIPE este publicat ca arhivă 7Z. PARTENER.EU păstrează documentul la sursa oficială, iar Q&A-ul AM PEO este atașat separat deoarece conține clarificări material importante față de versiunea de consultare.</p><div class="almaDocs">${DOCS.map((d,i)=>`<div class="almaDoc"><div class="almaDocNo">${i+1}</div><div class="almaDocBody"><b>${esc(d.name)}</b><span>${esc(d.meta)}</span></div><a href="${esc(d.url)}" target="_blank" rel="noreferrer">Deschide / descarcă ↗</a></div>`).join('')}</div></section>
<section class="almaBlock"><h2>Surse și proveniență</h2><div class="almaSources"><a href="${OIR}" target="_blank" rel="noreferrer"><b>OIR PECU Nord‑Vest — lansare oficială 27.05.2026</b><span>Confirmă apelul, pachetul de ghid și perioada MySMIS.</span></a><a href="${PREF}" target="_blank" rel="noreferrer"><b>Instituția Prefectului — catalog oficial de finanțări iunie 2026</b><span>Confirmă bugetul, valorile proiectelor, categoriile eligibile și acoperirea națională.</span></a><a href="${EC}" target="_blank" rel="noreferrer"><b>Comisia Europeană — ALMA</b><span>Descrie mecanismul european, costurile participantului și cele trei faze ale intervenției.</span></a><a href="${QA}" target="_blank" rel="noreferrer"><b>AM PEO — Q&A final de consultare</b><span>Clarifică grupul țintă, parteneriatul, indicatorii, mobilitatea și regulile operaționale.</span></a></div></section>
</article>`;main.querySelector('.almaBack').onclick=()=>{const brand=document.querySelector('.brand');if(brand)brand.click();else location.reload()}}
function card(){return `<article class="almaCard" data-almaopen><div class="almaTop"><span>PEO · ALMA</span><span>TINERI NEET</span><span class="open">OPEN · 28 AUG</span></div><h3>Până la 850.000 € pentru ONG-uri, FPC, școli și alți operatori care lucrează cu tineri NEET</h3><p>Mobilitate 2–6 luni în UE · buget total 19,7 mil. € · proiecte de integrare pentru tineri NEET · dosar complet + documente.</p><div class="almaFoot"><span>27 mai 2026</span><b>Analiză completă →</b></div></article>`}
function inject(){const hero=document.querySelector('.hero');if(hero&&!document.querySelector('[data-almapromo]')){const wrap=document.createElement('section');wrap.className='section almaPromo';wrap.dataset.almapromo='1';wrap.innerHTML=`<div class="eyebrow">PEO · oportunitate prioritară</div><h2>Inițiativa ALMA — tineri NEET</h2>${card()}`;const dr=document.querySelector('[data-dr14promo]');(dr||hero).insertAdjacentElement('afterend',wrap);wrap.querySelector('[data-almaopen]').onclick=render}const list=document.querySelector('.newsList');if(list&&!list.querySelector('[data-almaopen]')){const w=document.createElement('div');w.innerHTML=card();const c=w.firstElementChild;list.insertAdjacentElement('afterbegin',c);c.onclick=render}}
const obs=new MutationObserver(inject);obs.observe(document.getElementById('app'),{childList:true,subtree:true});inject();
})();