window.PARTENER_DATA = {
  asOf: '2026-08-11T14:34:00+03:00',
  calls: [
    {
      id:'afir-energy-2026', programme:'AFIR / Fondul pentru Modernizare', code:'Schema ENERGIE 2026',
      title:'Investiții în producerea energiei electrice din surse regenerabile pentru autoconsum',
      status:'OPEN', category:'Energie', region:'România', applicant:['Întreprinderi agricole','Industria alimentară'],
      applicantKeys:['agricultural_enterprise','food_industry_enterprise'], objectiveKeys:['renewable_energy','energy_autoconsumption'],
      open:'15 iunie 2026', close:'14 august 2026', budget:'265 mil. EUR', grant:'100% nerambursabil în limitele/MW', cofinancing:'0% în limitele schemei',
      summary:'Capacități noi de producere a energiei electrice din surse solare, cu sau fără stocare, pentru autoconsum.',
      eligibility:['Solicitant din sectorul agricol sau industria alimentară','Investiție în capacitate nouă pentru autoconsum','Respectarea condițiilor și plafoanelor din Schema de Energie'],
      activities:['Panouri fotovoltaice','Sisteme de stocare asociate','Echipamente și lucrări aferente capacității eligibile'], costs:['Echipamente pentru producerea energiei','Stocare eligibilă conform ghidului','Lucrări și instalații eligibile conform ghidului'], documents:['Cerere de finanțare v1.0/2026','Documente solicitant','Documentația tehnică solicitată de ghid'], scoring:['Eligibilitate și selecție conform Ghidului Schemei de Energie'], indicators:['Capacitate nouă instalată (MW)','Energie regenerabilă pentru autoconsum'], risks:['Încadrare sectorială incorectă','Documentație tehnică incompletă','Nerespectarea plafoanelor/MW'],
      sourceFacts:[{label:'AFIR — Deschiderea sesiunii, 15.06.2026', url:'https://www.afir.ro/comunicate/deschiderea-sesiunii-pentru-investitiile-in-producerea-energiei-electrice-din-surse-regenerabile/', tier:'T1'},{label:'AFIR — Ghid / buget 265 mil. EUR, 09.06.2026', url:'https://www.afir.ro/comunicate/265-de-milioane-de-euro-pentru-investitii-in-producerea-energiei-electrice/', tier:'T1'}],
      changes:[{date:'15 iun 2026', kind:'CALL_OPENED', before:'Ghid publicat', after:'Sesiune deschisă până la 14 aug 2026'},{date:'9 iun 2026', kind:'GUIDE_PUBLISHED', before:'—', after:'Ghid aprobat; buget 265 mil. EUR'}]
    },
    {
      id:'pr-centru-digital-2', programme:'Programul Regiunea Centru', code:'Acțiunea 2.2 — Apel 2', title:'Întreprinderi digitale pentru o economie avansată — Apel 2', status:'PUBLIC_CONSULTATION', category:'Digitalizare', region:'Centru', applicant:['Microîntreprinderi','Întreprinderi mici','Întreprinderi mijlocii'], applicantKeys:['microenterprise','small_enterprise','medium_enterprise'], objectiveKeys:['digitalization'], open:'—', close:'—', consultation:'28 aprilie – 20 mai 2026', budget:'14,113 mil. EUR', grant:'15.000–200.000 EUR', cofinancing:'min. 10%', summary:'Sprijin pentru digitalizarea IMM-urilor din Regiunea Centru. Starea oficială observată rămâne consultare publică.', eligibility:['IMM din Regiunea Centru','CAEN eligibil — necesită verificarea anexei autoritative','Condiții de minimis și sănătate financiară'], activities:['Digitalizarea proceselor','Software / ERP / automatizare','Investiții digitale eligibile conform ghidului'], costs:['Cheltuieli eligibile conform ghidului în consultare'], documents:['Documente conform ghidului în consultare'], scoring:['Prag ETF observat: 50 puncte','Mecanism de selecție conform ghidului'], indicators:['Indicatori de digitalizare conform ghidului'], risks:['Apelul nu este confirmat OPEN','CAEN neconfirmat fără Anexa 3','Condiții de minimis'], sourceFacts:[{label:'ADR Centru — pagina acțiunii 2.2 Apel 2',url:'https://www.regiocentru.ro/actiuni/2-2-intreprinderi-digitale-pentru-o-economie-avansata-apel-2/',tier:'T1'}], changes:[{date:'28 apr 2026',kind:'CONSULTATION_OPENED',before:'—',after:'Consultare publică până la 20 mai 2026'}]
    },
    {
      id:'pr-centru-clusters-122', programme:'Programul Regiunea Centru', code:'1.2.2', title:'Clustere inovative', status:'OPEN', category:'Inovare', region:'Centru', applicant:['Clustere / organizații eligibile conform ghidului'], applicantKeys:['cluster'], objectiveKeys:['innovation'], open:'6 iulie 2026, 12:00', close:'6 noiembrie 2026, 12:00', budget:'Vezi ghid', grant:'Vezi ghid', cofinancing:'Vezi ghid', summary:'Apel activ pentru clustere inovative în Regiunea Centru.', eligibility:['Conform ghidului specific'], activities:['Inovare și dezvoltare de cluster'], costs:['Conform ghidului'], documents:['Conform ghidului'], scoring:['Conform ghidului'], indicators:['Conform ghidului'], risks:['Verificarea formei eligibile a solicitantului'], sourceFacts:[{label:'ADR Centru — lista acțiunilor active',url:'https://www.regiocentru.ro/actiuni/',tier:'T1'}], changes:[{date:'6 iul 2026',kind:'CALL_OPENED',before:'Consultare',after:'OPEN'}]
    },
    {
      id:'pids-supported-decision', programme:'PIDS', code:'P07 / ESO4.11 / 7.2 C1', title:'Servicii de asistență și suport în luarea deciziei', status:'OPEN', category:'Social', region:'România', applicant:['Minister / parteneri instituționali eligibili'], applicantKeys:['ministry'], objectiveKeys:['social_services'], open:'30 iunie 2026, 16:00', close:'28 august 2026, 16:00', budget:'11,804 mil. EUR', grant:'Conform ghidului', cofinancing:'Conform ghidului', summary:'Apel PIDS necompetitiv pentru dezvoltarea serviciilor de suport în luarea deciziei.', eligibility:['Lider restricționat instituțional','Parteneri conform ghidului'], activities:['Servicii de suport'], costs:['Conform ghidului'], documents:['Conform ghidului final'], scoring:['Necompetitiv — condiții specifice'], indicators:['Conform ghidului'], risks:['IMM comercial obișnuit nu este solicitant eligibil'], sourceFacts:[{label:'OIR/AM PIDS — ghid final și lansare',url:'https://www.oirbi.ro/pids-2021-2027/',tier:'T1B'}], changes:[{date:'30 iun 2026',kind:'CALL_OPENED',before:'Ghid final',after:'OPEN'},{date:'25 iun 2026',kind:'GUIDE_PUBLISHED',before:'Consultare',after:'Ghid final'}]
    },
    {
      id:'peo-step-edu-adulti', programme:'PEO / STEP', code:'P11 / ESO4.7 / 11.g.1', title:'STEP-EDU — Competențe pentru viitor în tehnologii critice — Adulți', status:'EXPECTED', category:'Formare', region:'România', applicant:['Universități publice/private'], applicantKeys:['public_university','private_university'], objectiveKeys:['critical_technologies','adult_training'], open:'Neconfirmat', close:'Neconfirmat', consultation:'20 martie – 10 aprilie 2026', budget:'120 mil. EUR', grant:'Neconfirmat final', cofinancing:'Neconfirmat final', summary:'Obiect STEP observat în consultare; PARTENER.EU nu îl promovează la OPEN fără evidență autoritativă de lansare.', eligibility:['Solicitant principal: universități (observat în documentele de consultare)','Condițiile finale necesită ghid final'], activities:['Educația adulților în tehnologii critice'], costs:['Necunoscute până la ghid final'], documents:['Necunoscute până la ghid final'], scoring:['Necunoscut până la ghid final'], indicators:['Necunoscuți până la ghid final'], risks:['Confundarea consultării cu apel lansat'], sourceFacts:[{label:'OIR PECU — documente PEO / consultări STEP',url:'https://oirvest.ro/ghiduri-peo/',tier:'T1B'}], changes:[{date:'20 mar 2026',kind:'CONSULTATION_OPENED',before:'—',after:'Consultare; nu este OPEN'}]
    }
  ],
  clients:[
    {id:'alfa', name:'SC ALFA FOOD SRL', type:'food_industry_enterprise', county:'Vâlcea', region:'Sud-Vest Oltenia', objectives:['renewable_energy','digitalization'], completeness:82},
    {id:'beta', name:'Asociația BETA SOCIAL', type:'accredited_private_social_service_provider', county:'Brașov', region:'Centru', objectives:['social_services'], completeness:91}
  ]
};
