(()=>{
const D=window.PARTENER_DATA;if(!D)return;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]||c));
const month={ian:1,feb:2,mar:3,apr:4,mai:5,iun:6,iul:7,aug:8,sep:9,sept:9,oct:10,nov:11,dec:12};
function isoDate(s){const m=String(s||'').toLowerCase().match(/(\d{1,2})\s+([a-zăâîșț]+)\s+(20\d{2})/);if(!m)return '2000-01-01';const mo=month[m[2].slice(0,4)]||month[m[2].slice(0,3)]||1;return `${m[3]}-${String(mo).padStart(2,'0')}-${String(m[1]).padStart(2,'0')}`}
const kindLabel={CALL_OPENED:'APEL LANSAT',DEADLINE_EXTENDED:'TERMEN PRELUNGIT',GUIDE_PUBLISHED:'GHID PUBLICAT',GUIDE_MODIFIED:'GHID MODIFICAT',CONSULTATION_OPENED:'CONSULTARE',CALL_CLOSED:'APEL ÎNCHIS'};
function headline(c,e){if(e.kind==='DEADLINE_EXTENDED')return `${c.title}: termenul de depunere a fost prelungit`;if(e.kind==='CALL_OPENED')return `${c.title}: apelul este deschis`;if(e.kind==='GUIDE_PUBLISHED')return `${c.title}: ghidul a fost publicat`;if(e.kind==='GUIDE_MODIFIED')return `${c.title}: ghidul a fost modificat`;if(e.kind==='CONSULTATION_OPENED')return `${c.title}: consultare publică`;return `${c.title}: actualizare oficială`}
function programmeTag(c){const p=(c.programme||'').toLowerCase();if(p.includes('poids')||p.includes('pids'))return 'PoIDS';if(p.includes('peo'))return 'PEO';if(p.includes('afir'))return 'AFIR';if(p.includes('regional')||p.includes('regiunea')||p.includes('pr '))return 'REGIONAL';if(p.includes('tranziție')||p.includes('ptj'))return 'PTJ';return (c.programme||'ALTELE').split('/')[0].trim()}
function action(c,e){if(e.kind==='DEADLINE_EXTENDED')return 'Actualizează calendarul proiectului și lucrează numai cu noul termen oficial. Verifică dacă prelungirea modifică și alte documente ale apelului.';if(e.kind==='CALL_OPENED')return 'Verifică eligibilitatea, ghidul final și anexele curente înainte de a porni pregătirea cererii. Dacă organizația este potrivită, fixează imediat un plan de depunere.';if(e.kind==='CONSULTATION_OPENED')return 'Folosește perioada de consultare pentru pregătire și observații, dar nu trata apelul ca OPEN până la lansarea oficială.';if(e.kind==='GUIDE_PUBLISHED'||e.kind==='GUIDE_MODIFIED')return 'Descarcă versiunea curentă a ghidului și compară eligibilitatea, bugetul, criteriile și anexele cu versiunea folosită anterior.';return 'Verifică sursa oficială și actualizează decizia de proiect.'}
function impact(c){if(c.radarSV&&c.radarSV.audiences?.length)return `Relevant în special pentru ${c.radarSV.audiences.join(', ')} din Sud-Vest Oltenia. ${c.radarSV.note||''}`;if(c.applicant?.length)return `Afectează în primul rând: ${c.applicant.slice(0,4).join(', ')}.`;return `Afectează solicitanții și partenerii eligibili ai apelului ${c.code||''}.`}
function build(){const out=[];for(const c of D.calls||[]){for(const e of c.changes||[]){const id=`${c.id}-${e.kind}-${isoDate(e.date)}`.replace(/[^a-z0-9-]/gi,'-').toLowerCase();out.push({id,callId:c.id,date:e.date,iso:isoDate(e.date),kind:e.kind,tag:programmeTag(c),headline:headline(c,e),deck:`${e.before||'—'} → ${e.after||'Actualizare oficială'}`,what:`${e.after||c.summary||'A fost publicată o actualizare oficială.'}`,impact:impact(c),action:action(c,e),status:c.status,region:c.region,programme:c.programme,sv:!!c.radarSV,sources:(c.sourceFacts||[]).slice(0,3)})}}return out.sort((a,b)=>b.iso.localeCompare(a.iso)||a.headline.localeCompare(b.headline))}
D.news={items:build(),asOf:D.asOf,policy:'Canonical projection: news is generated from call events; no silent second copy of facts.'};
let filter='TOATE';
function visible(){return D.news.items.filter(n=>filter==='TOATE'||filter==='SV OLTENIA'&&n.sv||filter==='OPEN'&&n.status==='OPEN'||n.tag===filter)}
function card(n,featured=false){const urgent=n.kind==='DEADLINE_EXTENDED'?'urgent':n.status!=='OPEN'?'watch':'';return `<article class="newsCard ${featured?'featured':''}" data-news="${esc(n.id)}"><div class="newsKicker"><span class="newsTag ${urgent}">${esc(kindLabel[n.kind]||'UPDATE')}</span><span class="newsTag">${esc(n.tag)}</span>${n.sv?'<span class="newsTag">SV OLTENIA</span>':''}</div><h3>${esc(n.headline)}</h3><div class="newsDeck">${esc(n.deck)}</div><div class="newsDate">${esc(n.date)} · ${esc(n.programme||'')}</div></article>`}
function renderNews(){const main=document.querySelector('.main');if(!main)return;const list=visible();main.innerHTML=`<section class="newsHero"><div class="eyebrow">Funding News · Version Intelligence</div><h1>Știri & Schimbări</h1><p>Nu publicăm articole izolate de adevărul operațional. Fiecare știre este o proiecție a unui eveniment canonic din apel, cu sursa oficială și impactul practic.</p><div class="newsFilters">${['TOATE','PEO','PoIDS','REGIONAL','AFIR','PTJ','SV OLTENIA','OPEN'].map(x=>`<button class="newsFilter ${filter===x?'active':''}" data-newsfilter="${esc(x)}">${esc(x)}</button>`).join('')}</div></section><section class="newsList">${list.length?list.map(n=>card(n,false)).join(''):'<div class="newsEmpty">Nu există încă evenimente canonice în filtrul selectat.</div>'}</section>`;bindNews(main)}
function renderArticle(id){const n=D.news.items.find(x=>x.id===id);if(!n)return;const main=document.querySelector('.main');if(!main)return;main.innerHTML=`<article class="newsArticle"><div class="newsArticleHead"><button class="btn ghost newsBack" data-newsback>← Înapoi la știri</button><div class="newsKicker"><span class="newsTag">${esc(n.tag)}</span><span class="newsTag">${esc(kindLabel[n.kind]||'UPDATE')}</span>${n.sv?'<span class="newsTag">SV OLTENIA</span>':''}</div><h1>${esc(n.headline)}</h1><div class="newsArticleMeta"><span>${esc(n.date)}</span><span>·</span><span>${esc(n.programme||'')}</span><span>·</span><span>${esc(n.region||'')}</span></div></div><div class="newsArticleBody"><section class="newsBlock"><h2>Ce s-a întâmplat</h2><p>${esc(n.what)}</p></section><section class="newsBlock"><h2>Pe cine afectează</h2><p>${esc(n.impact)}</p></section><section class="newsBlock"><h2>Ce trebuie făcut acum</h2><p>${esc(n.action)}</p></section><section class="newsBlock"><h2>Surse oficiale</h2><div class="newsSourceList">${n.sources.length?n.sources.map(s=>`<div class="newsSource"><div><b>${esc(s.label)}</b><div class="meta">${esc(s.tier||'T1')} · provenance</div></div><a href="${esc(s.url)}" target="_blank" rel="noreferrer">Deschide sursa</a></div>`).join(''):'<div class="meta">Sursa nu este încă atașată evenimentului canonic.</div>'}</div></section></div></article>`;main.querySelector('[data-newsback]').onclick=renderNews}
function bindNews(root=document){root.querySelectorAll('[data-news]').forEach(x=>x.onclick=()=>renderArticle(x.dataset.news));root.querySelectorAll('[data-newsfilter]').forEach(x=>x.onclick=()=>{filter=x.dataset.newsfilter;renderNews()})}
function inject(){const nav=document.querySelector('.navlinks');if(nav&&!nav.querySelector('[data-newsnav]')){const b=document.createElement('button');b.className='navlink';b.dataset.newsnav='1';b.textContent='Știri';b.onclick=renderNews;nav.appendChild(b)}const hero=document.querySelector('.hero');if(hero&&!document.querySelector('[data-newspromo]')){const top=D.news.items.slice(0,5);if(!top.length)return;const section=document.createElement('section');section.className='section newsPromo';section.dataset.newspromo='1';section.innerHTML=`<div class="newsHead"><div><div class="eyebrow">Știri & Schimbări</div><h2>Ce s-a schimbat și ce trebuie făcut</h2><div class="sectionDesc">Generat din evenimente canonice, cu surse oficiale.</div></div><button class="btn secondary" data-newsall>Vezi toate</button></div><div class="newsGrid">${top.map((n,i)=>card(n,i===0)).join('')}</div>`;const promo=document.querySelector('[data-svpromo]');(promo||hero).insertAdjacentElement('afterend',section);section.querySelector('[data-newsall]').onclick=renderNews;bindNews(section)}}
const obs=new MutationObserver(()=>inject());obs.observe(document.getElementById('app'),{childList:true,subtree:true});inject();
})();