(()=>{
const D=window.PARTENER_DATA;
if(!D||!Array.isArray(D.calls))return;
const REGIONS=[
 {id:'nord-est',name:'Nord-Est',aliases:['nord-est','nord est'],counties:'Bacău · Botoșani · Iași · Neamț · Suceava · Vaslui'},
 {id:'sud-est',name:'Sud-Est',aliases:['sud-est','sud est'],counties:'Brăila · Buzău · Constanța · Galați · Tulcea · Vrancea'},
 {id:'sud-muntenia',name:'Sud-Muntenia',aliases:['sud-muntenia','sud muntenia'],counties:'Argeș · Călărași · Dâmbovița · Giurgiu · Ialomița · Prahova · Teleorman'},
 {id:'sud-vest-oltenia',name:'Sud-Vest Oltenia',aliases:['sud-vest oltenia','sud vest oltenia','oltenia'],counties:'Dolj · Gorj · Mehedinți · Olt · Vâlcea'},
 {id:'vest',name:'Vest',aliases:['regiunea vest','regional vest',' vest'],counties:'Arad · Caraș-Severin · Hunedoara · Timiș'},
 {id:'nord-vest',name:'Nord-Vest',aliases:['nord-vest','nord vest'],counties:'Bihor · Bistrița-Năsăud · Cluj · Maramureș · Satu Mare · Sălaj'},
 {id:'centru',name:'Centru',aliases:['regiunea centru','regional centru',' centru'],counties:'Alba · Brașov · Covasna · Harghita · Mureș · Sibiu'},
 {id:'bucuresti-ilfov',name:'București-Ilfov',aliases:['bucurești-ilfov','bucuresti-ilfov','bucurești ilfov','bucuresti ilfov'],counties:'Municipiul București · Ilfov'}
];
const AUDIENCES=['TOATE','FIRME','ONG','FPC','EDUCAȚIE','UAT','AGRICULTURĂ'];
let selected=null,audience='TOATE';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c));
const norm=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
const isBI=r=>r.id==='bucuresti-ilfov';
function specificMatch(c,r){const hay=norm(`${c.region||''} ${c.programme||''}`);return r.aliases.some(a=>hay.includes(norm(a)));}
function nationalMatch(c,r){const hay=norm(`${c.region||''} ${c.summary||''}`);if(/regiuni(ile)? mai putin dezvoltate|less developed/.test(hay))return !isBI(r);if(/bucuresti.?ilfov exclus|fara bucuresti|exceptand bucuresti/.test(hay))return !isBI(r);return /\bnational\b|\bromania\b|toate regiunile|nivel national/.test(hay);}
function applicable(c,r){if(specificMatch(c,r))return 'REGIONAL';if(nationalMatch(c,r))return 'NAȚIONAL';return null;}
function audiences(c){const keys=(c.applicantKeys||[]).map(norm);const text=norm(`${(c.applicant||[]).join(' ')} ${c.category||''} ${c.title||''} ${c.programme||''}`);const out=[];
 if(keys.some(k=>['enterprise','microenterprise','employer','social_enterprise','industrial_park'].includes(k))||/imm|microintrepr|intreprinder|companii|angajator/.test(text))out.push('FIRME');
 if(keys.includes('ngo')||/ong|asociati|fundati/.test(text))out.push('ONG');
 if(keys.includes('training_provider')||/furnizor.*formare|fpc|formare profesionala/.test(text))out.push('FPC');
 if(keys.some(k=>['public_school','private_school','university'].includes(k))||/scoal|invatamant|universit|educati/.test(text))out.push('EDUCAȚIE');
 if(keys.some(k=>['public_authority','municipality','county_council'].includes(k))||/uat|municip|consili|autoritat|institutii publice/.test(text))out.push('UAT');
 if(/afir|agric|fermier|ferma|rural/.test(text))out.push('AGRICULTURĂ');
 return [...new Set(out)];}
function regionCalls(r){return D.calls.map(c=>({c,scope:applicable(c,r),aud:audiences(c)})).filter(x=>x.scope).filter(x=>audience==='TOATE'||x.aud.includes(audience)).sort((a,b)=>({OPEN:0,PUBLIC_CONSULTATION:1,EXPECTED:2,CLOSED:9}[a.c.status]??5)-({OPEN:0,PUBLIC_CONSULTATION:1,EXPECTED:2,CLOSED:9}[b.c.status]??5)||String(a.c.close||'').localeCompare(String(b.c.close||''),'ro'));}
function metrics(r){const all=D.calls.map(c=>({c,scope:applicable(c,r)})).filter(x=>x.scope);return {all,open:all.filter(x=>x.c.status==='OPEN').length,watch:all.filter(x=>x.c.status!=='OPEN'&&x.c.status!=='CLOSED').length,regional:all.filter(x=>x.scope==='REGIONAL').length,national:all.filter(x=>x.scope==='NAȚIONAL').length};}
function renderHub(){selected=null;audience='TOATE';const main=document.querySelector('.main');if(!main)return;main.innerHTML=`<section class="rrHubHero"><div class="eyebrow">Funding Intelligence · România</div><h1>Radare regionale</h1><p>8 radare construite pe aceeași regulă: fiecare regiune vede apelurile regionale confirmate în corpus și apelurile naționale care au aplicabilitate explicită. Apelurile destinate numai regiunilor mai puțin dezvoltate nu sunt atribuite automat București‑Ilfov.</p><div class="rrRegions">${REGIONS.map(r=>{const m=metrics(r);return `<button class="rrRegionCard" data-rr="${r.id}"><div class="rrCallTop"><span class="rrScope">REGIUNE</span><span class="rrStatus ${m.open?'OPEN':''}">${m.open} OPEN</span></div><h3>${esc(r.name)}</h3><p>${esc(r.counties)}</p><div class="rrMetrics"><div><b>${m.all.length}</b><span>urmărite</span></div><div><b>${m.regional}</b><span>regionale</span></div><div><b>${m.national}</b><span>naționale</span></div></div></button>`}).join('')}</div></section>`;main.querySelectorAll('[data-rr]').forEach(b=>b.onclick=()=>{selected=REGIONS.find(r=>r.id===b.dataset.rr);renderRegion()});}
function renderRegion(){if(!selected)return renderHub();const main=document.querySelector('.main');if(!main)return;const m=metrics(selected),list=regionCalls(selected);main.innerHTML=`<section class="rrRegionHero"><div class="rrRegionTop"><div><div class="eyebrow">Radar regional · ${esc(selected.name)}</div><h1>${esc(selected.name)}</h1><p>${esc(selected.counties)}. Sunt afișate numai oportunități deja existente în corpusul canonic PARTENER.EU; lipsa unui apel din listă nu este tratată ca dovadă că apelul nu există.</p></div><button class="btn ghost rrBack">← Toate regiunile</button></div><div class="rrSummary"><div><b>${m.all.length}</b><span>oportunități urmărite</span></div><div><b>${m.open}</b><span>OPEN</span></div><div><b>${m.regional}</b><span>apeluri regionale</span></div><div><b>${m.national}</b><span>apeluri naționale aplicabile</span></div></div></section><section class="section"><div class="rrFilters">${AUDIENCES.map(a=>`<button class="rrFilter ${audience===a?'active':''}" data-rra="${esc(a)}">${esc(a)}</button>`).join('')}</div><div class="rrNotice">Aplicabilitatea regională este fail-closed: un apel intră într-un radar prin teritoriu explicit sau prin caracter național explicit. Eligibilitatea concretă a unui solicitant rămâne cea din ghidul oficial.</div>${list.length?`<div class="rrGrid">${list.map(({c,scope,aud})=>`<article class="rrCall"><div class="rrCallTop"><span class="rrScope">${scope}</span><span class="rrStatus ${esc(c.status)}">${esc(String(c.status||'').replaceAll('_',' '))}</span></div><h3>${esc(c.title)}</h3><div class="meta">${esc(c.programme)} · ${esc(c.region||selected.name)}</div>${aud.length?`<div class="rrTags">${aud.map(a=>`<span class="rrAudience">${esc(a)}</span>`).join('')}</div>`:''}<div class="rrFacts"><div><small>Deadline / stare</small><b>${esc(c.status==='OPEN'?(c.close||'Confirmat deschis'):(c.consultation||c.close||'Monitorizare'))}</b></div><div><small>Buget / grant</small><b>${esc(c.grant&&c.grant!=='Vezi ghid'?c.grant:(c.budget||'Vezi ghidul'))}</b></div></div><p>${esc(c.summary||'Vezi detaliile apelului în Funding Explorer.')}</p><div class="rrCallFoot">${(c.sourceFacts||[])[0]?`<a class="rrSource" href="${esc(c.sourceFacts[0].url)}" target="_blank" rel="noreferrer">Sursa oficială ↗</a>`:'<span></span>'}<span>${esc(c.category||'Finanțare')}</span></div></article>`).join('')}</div>`:`<div class="rrEmpty">Nu există încă oportunități din corpusul actual care să treacă regulile de aplicabilitate pentru filtrul selectat. Radarul rămâne activ și se populează pe măsură ce intră surse oficiale verificate.</div>`}</section>`;main.querySelector('.rrBack').onclick=renderHub;main.querySelectorAll('[data-rra]').forEach(b=>b.onclick=()=>{audience=b.dataset.rra;renderRegion()});}
function inject(){const nav=document.querySelector('.navlinks');if(nav&&!nav.querySelector('[data-regional-radars]')){const b=document.createElement('button');b.className='navlink rrNav';b.dataset.regionalRadars='1';b.textContent='Radare regionale';b.onclick=renderHub;nav.appendChild(b)}const hero=document.querySelector('.hero');if(hero&&!document.querySelector('[data-rrpromo]')){const p=document.createElement('button');p.className='rrPromo';p.dataset.rrpromo='1';p.innerHTML='<b>Radare regionale</b><span>8 regiuni · apeluri regionale + apeluri naționale aplicabile →</span>';p.onclick=renderHub;hero.insertAdjacentElement('afterend',p)}}
D.regionalRadars={regions:REGIONS.map(r=>({id:r.id,name:r.name,counties:r.counties})),audiences:AUDIENCES,asOf:D.asOf||new Date().toISOString()};
const obs=new MutationObserver(inject);obs.observe(document.getElementById('app'),{childList:true,subtree:true});inject();
})();