const state={places:[],meta:null,filter:'all',query:''};
const typeLabels={restaurant:'Restaurant',fast_casual:'Rapid',cafe:'Cafenea',pub:'Pub',bar:'Bar',club:'Club',spa:'Spa',pool:'Piscină',leisure:'Relaxare',bakery:'Brutărie',dessert:'Desert'};
const typeMarks={restaurant:'R',fast_casual:'G',cafe:'C',pub:'P',bar:'B',club:'N',spa:'S',pool:'A',leisure:'L',bakery:'B',dessert:'D'};
function escapeHtml(value=''){return String(value).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));}
function operatorLabel(place){const op=place.operator||{};return op.verification_status==='verified'?op.legal_name:'în verificare';}
function priceLabel(place){const menu=place.offer?.menu||{};if(!menu.prices_public)return'de reverificat';const prices=menu.sample_prices||[];if(!prices.length)return'meniu verificat';const min=Math.min(...prices.map(item=>item.price_ron));return`de la ${min.toFixed(2).replace('.',',')} lei`;}
function searchableText(place){return[place.name,place.type,place.location?.address,place.location?.city,place.offer?.summary,...(place.offer?.cuisine||[]),...(place.offer?.highlights||[])].filter(Boolean).join(' ').toLocaleLowerCase('ro');}
function matches(place){return(state.filter==='all'||place.type===state.filter)&&(!state.query||searchableText(place).includes(state.query));}
function renderCard(place){const badges=(place.badges||[]).slice(0,2).map(b=>`<span class="badge">${escapeHtml(b)}</span>`).join('');return`<article class="place-card"><div class="card-visual"><div class="badges">${badges}</div><span class="type-mark" aria-hidden="true">${typeMarks[place.type]||'•'}</span></div><div class="card-body"><p class="eyebrow">${escapeHtml(typeLabels[place.type]||place.type)}</p><h3>${escapeHtml(place.name)}</h3><p class="location">${escapeHtml(place.location.address)}, ${escapeHtml(place.location.city)}</p><p class="card-summary">${escapeHtml(place.offer.summary)}</p><div class="card-facts"><div class="fact"><span>Program</span><strong>${escapeHtml(place.hours.display||'de confirmat')}</strong></div><div class="fact"><span>Prețuri</span><strong>${escapeHtml(priceLabel(place))}</strong></div><div class="fact"><span>Operator</span><strong>${escapeHtml(operatorLabel(place))}</strong></div></div><button class="card-open" type="button" data-place="${escapeHtml(place.id)}">Deschide fișa verificată</button></div></article>`;}
function renderPlaces(){const visible=state.places.filter(matches);document.querySelector('#place-grid').innerHTML=visible.map(renderCard).join('');document.querySelector('#empty-state').hidden=visible.length>0;}
function renderLead(){const lead=state.places.find(p=>p.badges?.includes('Nou deschis'))||state.places[0];if(!lead)return;document.querySelector('#lead-story').innerHTML=`<p class="card-kicker">NOU DESCHIS · VERIFICAT</p><h2>${escapeHtml(lead.name)} a intrat pe harta orașului.</h2><p>${escapeHtml(lead.editorial.dek)}</p><div class="lead-meta"><span>${escapeHtml(lead.opening?.display||'')}</span><span>·</span><span>${escapeHtml(lead.location.address)}</span></div><button type="button" data-place="${escapeHtml(lead.id)}">Citește ce știm</button>`;}
function renderCounters(){const withPrices=state.places.filter(p=>p.offer?.menu?.prices_public).length;const withOperator=state.places.filter(p=>p.operator?.verification_status==='verified').length;document.querySelector('#verified-count').textContent=state.places.length;document.querySelector('#price-count').textContent=withPrices;document.querySelector('#operator-count').textContent=withOperator;document.querySelector('#candidate-count').textContent=state.meta?.candidate_count??'—';}
function sourceList(place){return(place.sources||[]).map(source=>`<li><a href="${escapeHtml(source.url)}" target="_blank" rel="noopener">${escapeHtml(source.publisher)} — ${escapeHtml(source.name)}</a> <small>(verificat ${escapeHtml(source.last_checked_at)})</small></li>`).join('');}
function openPlace(id){const place=state.places.find(item=>item.id===id);if(!place)return;const menu=place.offer?.menu||{};const prices=menu.sample_prices||[];const priceBlock=prices.length?`<ul class="price-list">${prices.map(item=>`<li><span>${escapeHtml(item.item)}</span><strong>${Number(item.price_ron).toFixed(2).replace('.',',')} lei</strong></li>`).join('')}</ul>`:`<p class="status-note">${escapeHtml(menu.note||'Prețurile nu sunt încă verificate.')}</p>`;const op=place.operator||{};const opBlock=op.verification_status==='verified'?`<p><strong>${escapeHtml(op.legal_name)}</strong>${op.cui?` · CUI ${escapeHtml(op.cui)}`:''}${op.registration_number?` · ${escapeHtml(op.registration_number)}`:''}</p><p>${escapeHtml(op.relationship||'')}</p>`:'<p class="status-note">Operatorul juridic este în curs de verificare. Nu publicăm un nume presupus.</p>';document.querySelector('#dialog-content').innerHTML=`<div class="dialog-inner"><p class="eyebrow">FIȘĂ VERIFICATĂ · ${escapeHtml(place.last_verified_at)}</p><h2 id="dialog-title">${escapeHtml(place.name)}</h2><p class="dialog-dek">${escapeHtml(place.editorial.dek||place.offer.summary)}</p><section class="dialog-section"><h3>Unde și cum ajungi</h3><p>${escapeHtml(place.location.address)}, ${escapeHtml(place.location.city)}, județul ${escapeHtml(place.location.county)}</p><p>${escapeHtml(place.hours.display||'Programul trebuie confirmat direct.')}</p></section><section class="dialog-section"><h3>Ce se mănâncă</h3><p>${escapeHtml(place.offer.summary)}</p><p><strong>Repere:</strong> ${escapeHtml((place.offer.highlights||[]).join(' · '))}</p>${priceBlock}<small>${escapeHtml(menu.note||'')}</small></section><section class="dialog-section"><h3>Cine este în spate</h3>${opBlock}</section><section class="dialog-section"><h3>Contact</h3><p>${(place.contact.phone||[]).map(escapeHtml).join(' · ')||'Telefon de confirmat'}${place.contact.email?`<br>${escapeHtml(place.contact.email)}`:''}</p>${place.contact.website?`<p><a href="${escapeHtml(place.contact.website)}" target="_blank" rel="noopener">Site oficial →</a></p>`:''}</section><section class="dialog-section"><h3>Surse</h3><ul class="source-list">${sourceList(place)}</ul><p class="status-note">${escapeHtml(place.editorial.transparency_note)}</p></section></div>`;document.querySelector('#place-dialog').showModal();}
function renderCreators(creators){const grid=document.querySelector('#creator-grid');if(!creators.length){grid.innerHTML='<div class="creator-empty"><strong>0</strong><p>Niciun profil nu este încă public. Aceasta este o alegere editorială, nu o lipsă de funcționalitate: candidații rămân în backend până la verificarea conținutului local, a autenticității și a colaborărilor comerciale.</p></div>';return;}grid.innerHTML=creators.map(c=>`<article><h3>${escapeHtml(c.display_name)}</h3></article>`).join('');}
function injectStructuredData(){const graph=state.places.map(place=>({'@type':['Restaurant','LocalBusiness'],'@id':`https://valceaclar.ro/unde-iesim/${place.slug}`,'name':place.name,'url':place.contact.website||undefined,'telephone':place.contact.phone?.[0]||undefined,'address':{'@type':'PostalAddress','streetAddress':place.location.address,'addressLocality':place.location.city,'addressRegion':place.location.county,'addressCountry':'RO'},'servesCuisine':place.offer.cuisine||[]}));const script=document.createElement('script');script.type='application/ld+json';script.textContent=JSON.stringify({'@context':'https://schema.org','@graph':graph});document.head.appendChild(script);}
async function init(){try{const responses=await Promise.all([fetch('data/places.json'),fetch('data/creators.json'),fetch('data/meta.json')]);if(!responses.every(r=>r.ok))throw new Error('Date indisponibile');const placesDoc=await responses[0].json();const creatorsDoc=await responses[1].json();state.meta=await responses[2].json();state.places=placesDoc.places||[];renderLead();renderCounters();renderPlaces();renderCreators(creatorsDoc.creators||[]);injectStructuredData();}catch(error){document.querySelector('#place-grid').innerHTML=`<p class="status-note">Datele nu au putut fi încărcate. ${escapeHtml(error.message)}</p>`;}}
document.addEventListener('click',event=>{const trigger=event.target.closest('[data-place]');if(trigger)openPlace(trigger.dataset.place);const filter=event.target.closest('[data-filter]');if(filter){state.filter=filter.dataset.filter;document.querySelectorAll('[data-filter]').forEach(btn=>btn.classList.toggle('is-active',btn===filter));renderPlaces();}if(event.target.closest('.dialog-close'))document.querySelector('#place-dialog').close();});
document.querySelector('#place-dialog').addEventListener('click',event=>{if(event.target===event.currentTarget)event.currentTarget.close();});
document.querySelector('#search').addEventListener('input',event=>{state.query=event.target.value.trim().toLocaleLowerCase('ro');renderPlaces();});
init();
